name: "indexing-docs-directory"

on:
  push:
    branches: ["main"]

jobs:
  indexing-docs-directory:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Indexing docs directory
    steps:
      - uses: actions/checkout@v2
      - name: run collect-search-results
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i
          node src/assets/scripts/indexing_docs_directory.js
          git config --global user.name "indexing_bot"
          git config --global user.email "indexing_bot"
          git fetch --all
          git pull
          git add -A && git commit -m "indexing_bot: Indexing docs" || echo "Indexing_bot: nothing to commit"
          git push
        shell: bash
